### ISSUE TITLE
Issue with whatstasker

### ISSUE THREAD

**Issue by josep112** [abdulnine7/ChatBot-on-WhatsApp-in-5-easy-steps#3]
Hi Congratulations for the code, I followed all the steps but I was not able to do
 I do not receive any information when I send the whatsapp message. When I start a manually start in OnWhatsApp I see an error in variable 11, is there any way to debug the problem

**Comment by abdulnine7** [comment]
What was the error can you please copy paste error log or screenshot.

**Comment by josep112** [comment]
Hi,
http://54.94.224.238:8085/image/image1.png

**Comment by abdulnine7** [comment]
Your WhatsTasker App is not properly configured it is unable to retrieve the message received into %wt_message variable. Configure whatstasker give it root access and notification reading access permission manually.

**Comment by josep112** [comment]
Hi,
I have already done this, it is released on the system for whatstasker and tasker, when I get a message in whatsapp I see the permission being released on watstasker but nothing happens, any other ideas?

**Comment by abdulnine7** [comment]
Check whether whatstasker is configured properly and superuser permission is granted to it every time when a message is received in whatsapp. And before running it for first time run GetConvID in tasks to set conversation ID.
